version: "3.8"

services:
  classification-api:
    build:
      context: .
      target: development
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./src/api:/app/src/api
      - ./config:/app/config
      - ./tests:/app/tests
      - ./assets:/app/assets:ro # Read-only assets
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app

volumes:
  config-cache:
