# Aetherwave Configuration Schema
# This file defines the structure and validation rules for Aetherwave configuration

app:
  name: "Aetherwave"
  version: "1.0.0"
  description: "Media display engine for high-resolution artwork"

display:
  # Window and rendering settings
  window:
    width: 1920
    height: 1080
    fullscreen: true
    vsync: true
    target_fps: 60

  # Visual effects and transitions
  effects:
    fade_duration: 2.0
    transition_type: "fade" # fade, slide, dissolve
    background_color: "#000000"

  # Multi-monitor support (future)
  monitors:
    primary_display: 0
    extended_displays: []

classification:
  # Image analysis settings
  analysis:
    include_colors: true
    include_mood: true
    include_complexity: true
    confidence_threshold: 0.8

  # Color analysis
  colors:
    max_dominant_colors: 5
    color_tolerance: 10

  # Mood classification
  mood:
    categories:
      - "cinematic"
      - "vibrant"
      - "serene"
      - "dramatic"
      - "minimal"

assets:
  # Asset management (read-only)
  directories:
    images: "assets/images"
    metadata: "config/metadata"
    cache: "config/cache"

  # Supported formats
  supported_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".webp"

api:
  # Python service configuration
  service:
    host: "127.0.0.1"
    port: 8000
    timeout: 30

  # Endpoints
  endpoints:
    classify: "/classify"
    metadata: "/metadata"
    health: "/health"

logging:
  # Logging configuration
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  output:
    console: true
    file: false
    file_path: "logs/aetherwave.log"
